import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import NavBar from '../components/NavBar';

const TERMS = [
  {
    category: 'Energy',
    color: 'blue',
    icon: 'fa-bolt',
    items: [
      {
        term: 'kWh (Kilowatt-hour)',
        definition:
          'The standard unit for measuring electricity consumption. One kWh is the energy used by a 1,000-watt appliance running for one hour. Your energy monitor tracks consumption in kWh per zone.',
      },
      {
        term: 'Zone',
        definition:
          'A defined area or section of your facility, for example Main Kitchen, Dining Room, or Bar. Energy readings are recorded per zone so you can see exactly where consumption is highest.',
      },
      {
        term: 'Anomaly',
        definition:
          'An unusual spike or drop in energy consumption that falls outside your normal pattern. Anomalies are flagged automatically and may indicate equipment left on overnight, a fault, or an unexpected event.',
      },
      {
        term: 'Forecast',
        definition:
          'A prediction of your future energy consumption based on historical patterns, generated by the machine learning model. Useful for anticipating high-usage periods and planning accordingly.',
      },
      {
        term: 'Peak Demand',
        definition:
          'The highest level of electricity drawn from the grid at any single point in time. High peak demand can trigger extra charges on some tariffs, even if your total consumption is low.',
      },
      {
        term: 'Off-Peak Hours',
        definition:
          'Times of day when electricity tariffs are cheaper, typically overnight or early morning. Shifting energy-intensive tasks to off-peak hours can reduce your bill significantly.',
      },
    ],
  },
  {
    category: 'Waste',
    color: 'emerald',
    icon: 'fa-recycle',
    items: [
      {
        term: 'Waste Stream',
        definition:
          'A category of waste collected and processed together, such as Recycling, Compost, or Landfill. Tracking each stream separately helps identify where improvements can be made.',
      },
      {
        term: 'Diversion Rate',
        definition:
          'The percentage of total waste that is recycled or composted instead of going to landfill. A higher diversion rate means less environmental impact and lower disposal costs.',
      },
      {
        term: 'Contamination',
        definition:
          'When incorrect items are placed in a recycling or compost bin, such as food waste in paper recycling. Contamination can cause an entire bin load to be rejected and sent to landfill instead.',
      },
      {
        term: 'Compost / Organic Waste',
        definition:
          'Food scraps, vegetable peelings, and other biodegradable material diverted from landfill. Composting avoids methane production that would occur in landfill, reducing your carbon footprint.',
      },
      {
        term: 'Landfill',
        definition:
          'Waste that cannot be recycled or composted and is buried in the ground. Landfill produces methane as it decomposes, making it the most environmentally harmful disposal method.',
      },
    ],
  },
  {
    category: 'Carbon',
    color: 'green',
    icon: 'fa-leaf',
    items: [
      {
        term: 'tCO2 / tCO2e (Tonnes of CO2 equivalent)',
        definition:
          'The standard unit for measuring carbon emissions. It converts all greenhouse gases into an equivalent amount of CO2 for easy comparison. One tCO2e is roughly the carbon produced by driving 3,500 miles.',
      },
      {
        term: 'Carbon Footprint',
        definition:
          'The total greenhouse gas emissions caused by your facility\'s energy use and waste, expressed in tCO2e. Your Carbon page shows this broken down by source.',
      },
      {
        term: 'Carbon Offset',
        definition:
          'A reduction in emissions achieved through recycling and composting. When waste is diverted from landfill, it avoids methane production, which counts as a carbon saving against your footprint.',
      },
      {
        term: 'Net tCO2',
        definition:
          'Your carbon footprint after subtracting recycling and composting offsets. Net = Energy emissions minus waste offsets. This is the most meaningful number to track over time.',
      },
      {
        term: 'UK Grid Carbon Intensity',
        definition:
          'The amount of CO2 produced per unit of electricity generated in the UK. GreenPulse uses 0.233 kg CO2 per kWh, based on the UK national grid average. This figure improves as more renewables come online.',
      },
    ],
  },
  {
    category: 'AI Insights',
    color: 'purple',
    icon: 'fa-wand-magic-sparkles',
    items: [
      {
        term: 'AI Insight',
        definition:
          'A recommendation generated by GreenPulse\'s machine learning engine based on patterns in your energy and waste data. Each insight includes an estimated monthly saving and a confidence score.',
      },
      {
        term: 'Confidence Score',
        definition:
          'A percentage showing how certain the AI is about an insight. Above 85% is high confidence, 70 to 85% is medium. Scores are based on how clearly the pattern appears in your data.',
      },
      {
        term: 'Estimated Savings',
        definition:
          'The projected monthly saving in pounds if you act on an insight. Calculated from your actual consumption data and current energy rates.',
      },
      {
        term: 'Realized Savings',
        definition:
          'The total estimated savings from insights you have marked as applied. Shown on your Reports page as a confirmed figure.',
      },
      {
        term: 'Potential Savings',
        definition:
          'The estimated savings still available from pending insights you have not yet acted on. This is money still on the table.',
      },
      {
        term: 'Applied',
        definition:
          'An insight you have confirmed as acted upon. Once marked applied, its estimated saving is counted in your realized savings total and tracked in your reports.',
      },
      {
        term: 'Dismissed',
        definition:
          'An insight you have reviewed and decided not to act on, for example because it is not currently feasible. Dismissed insights are removed from your active list but kept in your history.',
      },
    ],
  },
  {
    category: 'Reports',
    color: 'orange',
    icon: 'fa-chart-bar',
    items: [
      {
        term: 'Savings Performance',
        definition:
          'A monthly chart showing realized savings from applied insights versus the potential savings still available from pending ones.',
      },
      {
        term: 'CO2e Reduced',
        definition:
          'The estimated tonnes of CO2 avoided as a result of acting on energy insights. Calculated from your realized savings using the UK grid carbon intensity.',
      },
      {
        term: 'Insights Log',
        definition:
          'A full history of every insight your team has applied or dismissed, including who took the action, when, and their reason.',
      },
    ],
  },
  {
    category: 'Platform',
    color: 'gray',
    icon: 'fa-gears',
    items: [
      {
        term: 'Organisation',
        definition:
          'Your business or site within GreenPulse. All energy readings, waste logs, insights, and goals are scoped to your organisation. Other organisations cannot see your data.',
      },
      {
        term: 'Goal',
        definition:
          'A sustainability target you set for your organisation, such as reducing energy use by 500 kWh this month. Progress is tracked automatically against your live data.',
      },
      {
        term: 'MANAGER role',
        definition:
          'Full access to your organisation\'s data. Can create goals, apply or dismiss insights, invite team members, and import data.',
      },
      {
        term: 'VIEWER role',
        definition:
          'Read-only access. Can view dashboards, energy data, waste logs, and insights but cannot make changes or invite others.',
      },
      {
        term: 'IoT (Internet of Things)',
        definition:
          'Connected devices such as smart meters and sensors that send live readings directly to GreenPulse. Your IoT API key is used to authenticate these devices securely.',
      },
      {
        term: 'IoT API Key',
        definition:
          'A unique secret key assigned to your organisation. Devices include this key in their requests so GreenPulse knows which organisation the data belongs to.',
      },
    ],
  },
];

const COLOR = {
  blue:    { bg: 'bg-blue-50',    text: 'text-blue-700',   icon: 'bg-blue-100 text-blue-600',   border: 'border-blue-100'   },
  emerald: { bg: 'bg-emerald-50', text: 'text-emerald-700',icon: 'bg-emerald-100 text-emerald-600', border: 'border-emerald-100' },
  green:   { bg: 'bg-green-50',   text: 'text-green-700',  icon: 'bg-green-100 text-green-600',  border: 'border-green-100'  },
  purple:  { bg: 'bg-purple-50',  text: 'text-purple-700', icon: 'bg-purple-100 text-purple-600',border: 'border-purple-100' },
  orange:  { bg: 'bg-orange-50',  text: 'text-orange-700', icon: 'bg-orange-100 text-orange-500',border: 'border-orange-100' },
  gray:    { bg: 'bg-gray-50',    text: 'text-gray-700',   icon: 'bg-gray-100 text-gray-600',    border: 'border-gray-200'   },
};

export default function GlossaryPage() {
  const { user } = useAuth();
  const [search, setSearch] = useState('');
  const [activeCategory, setActiveCategory] = useState('All');

  const q = search.toLowerCase().trim();
  const categories = ['All', ...TERMS.map(g => g.category)];

  const filtered = TERMS.map(group => ({
    ...group,
    items: group.items.filter(
      item =>
        (activeCategory === 'All' || group.category === activeCategory) &&
        (!q || item.term.toLowerCase().includes(q) || item.definition.toLowerCase().includes(q))
    ),
  })).filter(g => g.items.length > 0);

  const totalTerms = TERMS.reduce((n, g) => n + g.items.length, 0);

  return (
    <div className="bg-gray-50 min-h-screen">
      {user && <NavBar />}

      {/* Header */}
      <div className="bg-white border-b border-gray-200">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
          {!user && (
            <div className="flex items-center justify-between mb-6">
              <Link to="/" className="flex items-center gap-2 text-gray-600 hover:text-gray-900">
                <div className="w-7 h-7 rounded-lg bg-emerald-500 flex items-center justify-center text-white text-sm">
                  <i className="fa-solid fa-leaf"></i>
                </div>
                <span className="font-bold text-gray-900">GreenPulse</span>
              </Link>
              <Link to="/signin" className="text-sm text-emerald-600 font-medium hover:underline">Sign in</Link>
            </div>
          )}
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 rounded-xl bg-emerald-100 flex items-center justify-center text-emerald-600 flex-shrink-0">
              <i className="fa-solid fa-book-open text-xl"></i>
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900 mb-1">Glossary</h1>
              <p className="text-sm text-gray-500">{totalTerms} terms across energy, waste, carbon, and platform concepts — plain English, no jargon.</p>
            </div>
          </div>

          {/* Search */}
          <div className="mt-6 relative">
            <i className="fa-solid fa-magnifying-glass absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-sm"></i>
            <input
              type="text"
              placeholder="Search terms..."
              value={search}
              onChange={e => setSearch(e.target.value)}
              className="w-full pl-9 pr-4 py-2.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500 bg-gray-50"
            />
          </div>

          {/* Category pills */}
          <div className="mt-4 flex flex-wrap gap-2">
            {categories.map(cat => (
              <button
                key={cat}
                onClick={() => setActiveCategory(cat)}
                className={`px-3 py-1 rounded-full text-xs font-semibold transition-colors ${
                  activeCategory === cat
                    ? 'bg-emerald-600 text-white'
                    : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Terms */}
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-10">
        {filtered.length === 0 && (
          <div className="text-center py-16 text-gray-400">
            <i className="fa-solid fa-magnifying-glass text-4xl mb-3 opacity-30"></i>
            <p className="text-sm">No terms match your search.</p>
          </div>
        )}

        {filtered.map(group => {
          const c = COLOR[group.color] ?? COLOR.gray;
          return (
            <div key={group.category}>
              {/* Section header */}
              <div className="flex items-center gap-3 mb-4">
                <div className={`w-8 h-8 rounded-lg flex items-center justify-center text-sm ${c.icon}`}>
                  <i className={`fa-solid ${group.icon}`}></i>
                </div>
                <h2 className={`text-base font-bold ${c.text}`}>{group.category}</h2>
                <div className="flex-1 h-px bg-gray-200"></div>
                <span className="text-xs text-gray-400">{group.items.length} term{group.items.length !== 1 ? 's' : ''}</span>
              </div>

              {/* Cards */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {group.items.map(item => (
                  <div
                    key={item.term}
                    className={`bg-white rounded-xl border ${c.border} p-5 hover:shadow-sm transition-shadow`}
                  >
                    <h3 className="text-sm font-bold text-gray-900 mb-2">{item.term}</h3>
                    <p className="text-sm text-gray-600 leading-relaxed">{item.definition}</p>
                  </div>
                ))}
              </div>
            </div>
          );
        })}

        {/* Footer note */}
        <div className="border-t border-gray-200 pt-8 text-center">
          <p className="text-xs text-gray-400">
            Something unclear?{' '}
            <Link to="/contact" className="text-emerald-600 hover:underline">Contact us</Link> and we will add it here.
          </p>
        </div>
      </div>
    </div>
  );
}
